query {
  organization(login: "NCBI-Hackathons") {
    login
    repositories(first: 100) {
      totalCount
      nodes {
        name
        description
        url
        languages(first: 1) {
          edges {
            node {
              name
            }
          }
        }
        releases(first: 1) {
          totalCount
        }
        issues(first: 100, labels: "manuscript") {
          edges {
            node {
              body
            }
          }
        }
      }
    }
  }
}
