query {
  organization(login: "NCBI-Hackathons") {
    login
    repositories(first: 100) {
      totalCount
      nodes {
        name
        description
        url
        releases(first: 1) {
          totalCount
        }
        pushedAt
        primaryLanguage {
          name
          color
        }
        issues(first: 100, labels: ["manuscript", "title"]) {
          edges {
            node {
              title
              body
            }
          }
        }
      }
    }
  }
}
